# Generated by Django 2.2.12 on 2025-05-11 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('area', models.CharField(choices=[('DESENVOLVEDOR', 'Desenvolvedor'), ('QA', 'Tester'), ('LIDER', 'Lider Técnico')], max_length=15)),
                ('tipo_contrato', models.CharField(choices=[('PJ', 'Pessoa Júrídica'), ('CLT', 'CLT')], max_length=15)),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('email', models.CharField(max_length=50)),
                ('escolaridade', models.CharField(choices=[('ENSINO_FUNDAMENTAL', 'Ensino Fundamental'), ('ENSINO_MEDIO', 'Ensino Médio'), ('CURSO_TECNICO', 'Curso Técnico'), ('CURSO_SUPERIOR', 'Curso Superior')], max_length=50)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprego.Vaga')),
            ],
        ),
    ]
